# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-06 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, verbose_name='用户名')),
                ('email', models.EmailField(max_length=30, verbose_name='邮箱')),
                ('tel', models.CharField(max_length=12, verbose_name='手机号码')),
                ('passwd', models.CharField(max_length=20, verbose_name='密码')),
            ],
            options={
                'verbose_name': '用户',
            },
        ),
    ]
