# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-08 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0002_auto_20171108_1405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
