# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-09 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0006_auto_20171108_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default=True, upload_to='images/', verbose_name='照片'),
        ),
    ]
