# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-14 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0008_auto_20171109_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default=True, upload_to='media', verbose_name='照片'),
        ),
    ]
