# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-07 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vip_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='真实姓名')),
                ('city', models.CharField(max_length=20, verbose_name='所在城市')),
                ('sex', models.CharField(max_length=5, verbose_name='性别')),
                ('email', models.EmailField(max_length=20, verbose_name='邮箱')),
                ('ID_num', models.CharField(max_length=18, verbose_name='身份证')),
                ('intro', models.CharField(max_length=200, verbose_name='简介')),
            ],
        ),
    ]
