# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-07 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_vip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vip_user',
            name='photo',
            field=models.ImageField(default=True, upload_to='', verbose_name='照片'),
        ),
    ]
