# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-08 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('df_user', '0006_auto_20171108_1511'),
        ('df_vip', '0004_auto_20171108_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vip_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='收货人')),
                ('city', models.CharField(max_length=20, verbose_name='地区')),
                ('address', models.CharField(max_length=100, verbose_name='街道地址')),
                ('code', models.EmailField(max_length=6, verbose_name='邮编')),
                ('tel', models.CharField(max_length=18, verbose_name='电话')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_user.User')),
            ],
        ),
    ]
