# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-10 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_good', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pro_body',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=20, verbose_name='品牌')),
                ('pversion', models.CharField(max_length=20, verbose_name='型号')),
                ('pcolor', models.CharField(max_length=20, verbose_name='颜色')),
                ('pmarket_time', models.DateTimeField(verbose_name='上市时间')),
                ('input_mode', models.CharField(max_length=20, verbose_name='输入方式')),
                ('smart_phone', models.BooleanField(default=True, verbose_name='智能机')),
                ('call_mode_3G', models.BooleanField(default=True, verbose_name='3G视频通话')),
                ('systerm', models.CharField(max_length=20, verbose_name='操作系统')),
                ('CPU_mode', models.CharField(max_length=20, verbose_name='CPU型号')),
                ('CPU_frequency', models.CharField(max_length=20, verbose_name='CPU频率')),
                ('CPU_kerenl', models.IntegerField(verbose_name='CPU核数')),
                ('operator', models.CharField(max_length=20, verbose_name='运营商')),
            ],
            options={
                'verbose_name': '产品主体',
                'verbose_name_plural': '产品主体',
            },
        ),
        migrations.DeleteModel(
            name='GoodsInfo',
        ),
    ]
