# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-10 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_good', '0002_auto_20171110_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro_body',
            name='pphoto',
            field=models.ImageField(default='', upload_to='goods', verbose_name='照片'),
        ),
    ]
