# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-12 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_good', '0004_auto_20171112_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro_body',
            name='pcomment',
            field=models.CharField(default='', max_length=100, verbose_name='评论'),
        ),
        migrations.AddField(
            model_name='pro_body',
            name='pprice',
            field=models.CharField(default='', max_length=20, verbose_name='价格'),
        ),
    ]
