# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-12 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_good', '0005_auto_20171112_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro_body',
            name='pphoto',
            field=models.ImageField(default='', upload_to='goods', verbose_name='照片'),
        ),
    ]
